### ISSUE TITLE
Not enough memory?

### ISSUE THREAD

**Issue by huyicen** [battlecatsultimate/bcu-resources#1]
When i boot up the BCUinstaller.jar, It always say this：“**Not enough memory , Current memory : 247MB**”
But I have 7.7GB of ram and 26GB of empty disk space

**Comment by MandarinSmell** [comment]
Check if your java is installed properly, if you installed Java 32bit in 64bit OS, it can show such error

**Comment by ghost** [comment]
who are you------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;huyicen&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月9日(星期六) 晚上9:55
收件人:&nbsp;&quot;battlecatsultimate/bcu-resources&quot;<bcu-resources@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [battlecatsultimate/bcu-resources] Not enough memory? (#1)

**Comment by huyicen** [comment]
> who are you------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;&quot;huyicen&quot;<notifications@github.com&gt; 发送时间:&nbsp;2021年1月9日(星期六) 晚上9:55 收件人:&nbsp;&quot;battlecatsultimate/bcu-resources&quot;<bcu-resources@noreply.github.com&gt;; 抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;; 主题:&nbsp;Re: [battlecatsultimate/bcu-resources] Not enough memory? (#1)

Just a random BattleCats lover

**Comment by ghost** [comment]
Did you send the wrong email------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;huyicen&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月9日(星期六) 晚上9:55
收件人:&nbsp;&quot;battlecatsultimate/bcu-resources&quot;<bcu-resources@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [battlecatsultimate/bcu-resources] Not enough memory? (#1)

**Comment by ghost** [comment]
Why do you email me------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;huyicen&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月9日(星期六) 晚上9:59
收件人:&nbsp;&quot;battlecatsultimate/bcu-resources&quot;<bcu-resources@noreply.github.com&gt;;
抄送:&nbsp;&quot;buyoukanwo&quot;<1791168864@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [battlecatsultimate/bcu-resources] Not enough memory? (#1)

**Comment by huyicen** [comment]
> Did you send the wrong email------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;&quot;huyicen&quot;<notifications@github.com&gt; 发送时间:&nbsp;2021年1月9日(星期六) 晚上9:55 收件人:&nbsp;&quot;battlecatsultimate/bcu-resources&quot;<bcu-resources@noreply.github.com&gt;; 抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;; 主题:&nbsp;Re: [battlecatsultimate/bcu-resources] Not enough memory? (#1)

Sorry :(
