### ISSUE TITLE
Android app completely disappeared 

### ISSUE THREAD

**Issue by AudreyChie** [battlecatsultimate/bcu-resources#2]
The title is already self-explanatory, but I just downloaded the BCU android app, and I left it overnight to download files. Then, when I woke up and it was done, I exited out of it. I was trying to use the app again before I found it literally wasn't there anymore, including the Leaks app that came with it. Even weirder, I actually still have it installed on my phone, but it just doesn't appear on my home screen and there's no way to me to launch it. is this a problem from the devs or android itself? And is there a fix?

**Comment by huyicen** [comment]
Yeah me too.
But somehow its on my desktop on my **3rd attempt.**....maybe try again?

**Comment by MandarinSmell** [comment]
It seems some OS can't handle sub-app system. Leak is BCU Android's sub-app which can catch memory leak. Memory leak is really critical bug, so I made BCU Android install additional app. The only way to solve this problem is :

1. Download 0.15.5
2. Get external launcher app (Ex. Nova Launcher, etc)

These 2 ways will be able to solve your problem
Close issue if you solved problem

**Comment by ghost** [comment]
Did you send the wrong e-mail------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;AudreyChie&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月15日(星期五) 晚上7:42
收件人:&nbsp;&quot;battlecatsultimate/bcu-resources&quot;<bcu-resources@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[battlecatsultimate/bcu-resources] Android app completely disappeared  (#2)

**Comment by ghost** [comment]
can you speak chinese？------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Mandarin&amp;nbsp;Smell&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月15日(星期五) 晚上7:47
收件人:&nbsp;&quot;battlecatsultimate/bcu-resources&quot;<bcu-resources@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [battlecatsultimate/bcu-resources] Android app completely disappeared  (#2)

**Comment by MandarinSmell** [comment]
I think you set notification or something? It's not our fault that email was sent to you

**Comment by ghost** [comment]
no------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Mandarin&amp;nbsp;Smell&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月15日(星期五) 晚上8:16
收件人:&nbsp;&quot;battlecatsultimate/bcu-resources&quot;<bcu-resources@noreply.github.com&gt;;
抄送:&nbsp;&quot;buyoukanwo&quot;<1791168864@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [battlecatsultimate/bcu-resources] Android app completely disappeared  (#2)

**Comment by ghost** [comment]
Did you send the wrong e-mail again------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;huyicen&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月15日(星期五) 晚上7:45
收件人:&nbsp;&quot;battlecatsultimate/bcu-resources&quot;<bcu-resources@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [battlecatsultimate/bcu-resources] Android app completely disappeared  (#2)

**Comment by ghost** [comment]
Which account was your e-mail supposed to go to------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Mandarin&amp;nbsp;Smell&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月15日(星期五) 晚上8:16
收件人:&nbsp;&quot;battlecatsultimate/bcu-resources&quot;<bcu-resources@noreply.github.com&gt;;
抄送:&nbsp;&quot;buyoukanwo&quot;<1791168864@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [battlecatsultimate/bcu-resources] Android app completely disappeared  (#2)

**Comment by MandarinSmell** [comment]
Just open github webpage and find a way to turn off that email notif, we aren't using any email thing to send this. You are making issue page messy, stop commenting with email

**Comment by MandarinSmell** [comment]
Closing issue because of inactiveness
